name: Spiritual Escorts
favicon: null
layout_spectrum: 0.4771696988027543
typography_spectrum: 0.34792620898224413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.05043294350616634
  lightness: 0.3539929713588208
  saturation: 0.4291845590341836
  rhythmicContrast: 0.2841887625399977
purpose: []
